# organization repository (?)
organization: false

# site title
title: 点点行行

# user name or organization name
user: wellls

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 5#2fed925ba1f6c8adf7bf3925d42d83f5ed3ff02 

# posts per page
perpage: 8

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
