# site title
title: 点点行行

# user name or organization name
user: wellls

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 80e9dfa35adaf5e6b287cac670d08f405af8e2ce 

# posts per page
perpage: 8


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
