# organization repository (?)
organization: false

# site title
title: 点点行行

# user name or organization name
user: wellls

# issue repository
repository: blog

# multi-author
authors: wellls

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: b#8e3b9a3519185f231eb13074fb4927529c7e868 

# posts per page
perpage: 8

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'

